base_path_data: "/albedo/work/projects/p_forclima/preproc_data_esmvaltool"

datasets: [
  {
    base_dir: "LGM", 
    exp: "lgm",
    variables: ["tas", "tos"], 
    aliases: ["lgm"],
    statistics: ["CLIM"], # optional (but if not given, subdirs must be given!)
    subset: {             # optional
      base_subdirs: ["20241114"],
      level_shared: "member"
    }
  },
  {
    base_dir: "historical", # required
    exp: "historical", # required
    variables: ["tas", "tos"], # required
    aliases: ["historical"], # required
    statistics: ["CLIM"], # optional (default: nothing)
    dir_per_var: true, # optional (default: true)
    subset: {
      base_subdirs: ["20250211", "20250207", "20250209"] # optional(default: empty) only applies when dir_per_var is true
    }
  }
]
