base_path_data: "/albedo/work/projects/p_forclima/preproc_data_esmvaltool"

datasets: [
  {
    base_dir: "ssp126",
    exp: "ssp126", 
    variables: ["tas", "psl"],
    statistics: ["CLIM-ann"], 
    aliases: ["ssp126"],
    subset: {
      base_subdirs: ["timeseries_20250226"]
    }
  },
  {
    base_dir: "ssp585",
    exp: "ssp585", 
    variables: ["tas", "psl"],
    statistics: ["CLIM-ann"], 
    aliases: ["ssp585"],
    subset: {
      base_subdirs: ["timeseries_20250226"]
    }
  },
  {
    base_dir: "historical",
    aliases: ["historical"],
    exp: "historical",
    variables: ["tas", "psl"], 
    statistics: ["CLIM-ann"],
    subset: {
      base_subdirs: ["timeseries_20250228", "timeseries_20250313"],
      timeseries: {start_y: 1980, end_y: 2014}
    }
  },
    {
    base_dir: "historical",
    aliases: ["historical"],
    exp: "historical",
    variables: ["tas", "psl"], 
    statistics: ["CLIM"]
  }
]