base_path_data: "/albedo/work/projects/p_forclima/preproc_data_esmvaltool"

datasets: [
  {
    base_dir: "LGM", 
    exp: "lgm", 
    variables: ["tas", "tos"],
    aliases: ["lgm"],
    statistics: ["CLIM"], 
    subset: {
      base_subdirs: ["20241114"]
    }
  },
  {
    base_dir: "piControl", 
    exp: "piControl", 
    variables: ["tas", "tos"],
    aliases: ["piControl"],  
    statistics: ["CLIM"],
    subset: {
      base_subdirs: ["lgm_models", "20250322"]
    }
  },
    {
    base_dir: "historical", 
    exp: "historical", 
    variables: ["tas", "tos"],
    aliases: ["historical"], 
    statistics: ["CLIM"]
  }
]
